language: minimal

services:
  - docker

env:
  - REPO=gothicfan/prometheus-twilio

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build . -t $REPO:$TRAVIC_BUILD_NUMBER -t $REPO:latest
  - docker push $REPO:$TRAVIC_BUILD_NUMBER
  - docker push $REPO:latest