language: minimal

services:
  - docker

env:
  - IMAGE=gothicfan/prometheus-twilio:$TRAVIS_BUILD_NUMBER

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build . -t $IMAGE
  - docker push $IMAGE